### ISSUE TITLE
Analysing CGAL 4.8 crashes mid way through

### ISSUE THREAD

**Issue by speps** [CoatiSoftware/CoatiBugTracker#77] opened 2016-05-14 08:47 UTC
Repro steps :

- Download [CGAL-4.8.zip](https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.8/CGAL-4.8.zip) and unzip into some folder
- Create new project with project paths of `CGAL-4.8\src` and `CGAL-4.8\include` and include paths of `CGAL-4.8\include`.
- Coati 0.6.0 (Windows 32 bits) crashes after analysing around ~1.6k files.

**Comment by mlangkabel** [comment] 2016-05-14 11:16
@speps thanks for reporting this! Do you know at which file the analysis crashes? To find out you can just open the last log file before the crash ([where to find it](https://www.coati.io/documentation/#Datafolder)) and search for the last occurrence of "INFO: STATUS analyzing files (ESC to quit)".
Can you try to analyze only this file? Just open the project settings and remove everything from the project paths but the path to this file. If it still crashes with those settings it helps to track down that bug a lot!

**Comment by speps** [comment] 2016-05-14 16:18
Here it is (removed personal data) :

`17:16:00 | StatusBarController.cpp:58 StatusBarController::setStatus() | INFO: STATUS analyzing files (ESC to quit): [1/1321] C:/Users/XXXXX/Documents/Work/CGAL/CGAL-4.8/include/CGAL/Epick_d.h`

**Comment by mlangkabel** [comment] 2016-05-17 09:41
Good news: We have been able to reproduce this crash. Thanks again @speps for the accurate info!

**Comment by mlangkabel** [comment] 2016-05-17 10:25
Bad news: The crash is caused by the clang compiler, not in our code. 

It seems like the Epick_d.h file is not included in any source file throughout the project. Therefore the usual compiler wouldn't even know that this file exists. Thus clang would not crash when just compiling this project.

Until now Coati alanyzes all the provided source files and all the headers that are directly or indirectly included by those source files. Afterwards it analyzes the headers that have not been visited yet. 

As this policy may cause problems (for example when certain headers shoud not be part of the project when building a certain configuration) we will alter this policy in the future and visit only those headers that are somehow included by source files, since that's what gets built.

These changes will be part of the next Coati release.

**Closed by mlangkabel** 2016-05-17 10:25 UTC
Labels: bug

**Comment by speps** [comment] 2016-05-17 10:27
Great! Thanks a lot! Really looking forward to the next release as for any
project I've tried so far there's been a problem :)

**Comment by mlangkabel** [comment] 2016-05-17 10:42
I can imagine that. @speps to solve your current problem you could just delete the Epick_d.h file and give it another try.
