### ISSUE TITLE
Unable to quit Coati from the initial screen

### ISSUE THREAD

**Issue by Imagix** [CoatiSoftware/CoatiBugTracker#227] opened 2016-10-14 18:50 UTC
When Coati starts up, it shows you a special splash screen to open a recent project.  While in this screen, one cannot quit the application.   You must first open a project before you can quit.

macOS Sierra, Coati v0.9.0

**Comment by egraether** [comment] 2016-10-14 18:57
Thanks for reporting, I can reproduce. I think it's caused by this recent setting on the start screen:
`this->setWindowModality(Qt::ApplicationModal);`

**Comment by mlangkabel** [comment] 2016-10-15 10:54
On Windows you can close the application by hitting esc (which causes the start screen to disappear) and closing the main window afterwards. Is this possible on mac, too?

**Comment by egraether** [comment] 2016-10-15 11:28
Yes, you can get rid of the start screen with ESC and then close the application on Mac too

**Comment by mlangkabel** [comment] 2016-10-15 16:40
Ok, but that's still not obvious. We should make the main window closable with the start screen open.

**Comment by egraether** [comment] 2016-10-20 10:33
Fixed with 0.9.8
`this->setWindowModality(Qt::ApplicationModal);` removed from start screen

**Closed by egraether** 2016-10-20 10:33 UTC
Labels: bug
