### ISSUE TITLE
re-analyzing a project gets stuck at "Loading Project:..."

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#84] opened 2016-05-23 10:38 UTC
Following lines are logged in the terminal:

QWaitCondition: cv destroy failure: Device or resource busy
QWaitCondition: mutex destroy failure: Device or resource busy

**Comment by egraether** [comment] 2016-05-23 12:47
Reportet on linux x64, manjaro 15.12

**Comment by mlangkabel** [comment] 2016-12-14 15:33
We have been unable to reproduce this issue. It hasn't been reported again in the last 7 month, so we are closing this issue now.

**Closed by mlangkabel** 2016-12-14 15:33 UTC
Labels: bug, Linux, nonreproducible
