### ISSUE TITLE
Unexpectedly closes(crashes) when to create a project from a Visual Studio sln file

### ISSUE THREAD

**Issue by rojaster** [CoatiSoftware/CoatiBugTracker#168] opened 2016-08-25 15:08 UTC
Hi, I have a problem with the Coati version 0.7.0.22 and ChakraCore sln file for Visual Studio.
https://github.com/Microsoft/ChakraCore/tree/master/Build

it is unexpectedly closed when I'm trying to create a project from a Visual Studio sln file.

**Comment by egraether** [comment] 2016-08-26 09:34
We have some problems with the current implementation and are already working on a better solution. I will let you know when it's ready.
Duplicate of #127

**Comment by wrongway88** [comment] 2016-10-14 11:52
The new Coati release contains an updated VS plugin version that adds the ability to create a Compilation Database from the VS solution. Solution parsing is handled from within VS, this method should be much more robust and stable.

Note that solution parsing is now done in VS via the plugin interface (see documentation for details). The resulting CDB still has to be loaded by hand in Coati, this process will be automated in the future.

**Comment by wrongway88** [comment] 2016-10-14 12:22
Update: after revisiting the linked project (ChakraCore) it turns out that some oddity in it's solution structure causes an issue with detecting VC projects. I'll release an update for that asap.

**Comment by wrongway88** [comment] 2016-10-31 11:59
@rojaster 
A new plugin version is included in the latest Coati version (0.9.23 https://www.coati.io/downloads).
I've tested ChakraCore myself so it should work now. Please let me know if you have any more problems.

**Comment by egraether** [comment] 2017-02-11 22:58
The project setup via Visual Studio plugin was tested on the reported code base. No reaction from reporter in 3 months. Closing now.

**Closed by egraether** 2017-02-11 22:58 UTC
Labels: await reply, bug, duplicate, Windows
