### ISSUE TITLE
Tooltips unreadable in dark scheme

### ISSUE THREAD

**Issue by pwinter1991** [CoatiSoftware/CoatiBugTracker#16] opened 2015-12-10 20:45 UTC
![coati-tooltip](https://cloud.githubusercontent.com/assets/5417215/11727950/4946830c-9f87-11e5-9ad3-6cc0838855f8.png)

**Comment by egraether** [comment] 2015-12-11 02:08
Can't reproduce on Mac. What platform are you using?

**Comment by pwinter1991** [comment] 2015-12-11 11:21
Probably a windows only thing. I tested it on Win8.1 and Win10.

**Comment by mlangkabel** [comment] 2015-12-11 11:33
I can reproduce it on Windows 7. So the chances are good that it will be fixed in the next release :)

**Comment by egraether** [comment] 2015-12-14 10:35
Fixed with 0.3.0.52
Apparently the tooltip background color can't be changed for Windows. We are using bright tooltips in every color scheme now.

**Closed by egraether** 2015-12-14 10:35 UTC
Labels: bug
