### ISSUE TITLE
Crash on Linux Mint on reindexing

### ISSUE THREAD

**Issue by DarianAnjuhal** [CoatiSoftware/CoatiBugTracker#105] opened 2016-06-24 17:02 UTC
Hey,

I changed the project options and excluded external libs like curl...etc.

During the reindexing the whole application crashes .

This is the shell output:
```
EventManager.cpp.
18:55:20 | PersistentStorage.cpp:352 logStats() | WARNING: 
Graph:
        4873 Nodes
        12573 Edges

Code:
        267 Files
        56990 Lines of Code

Errors:
        149 Errors
        12 Fatal Errors

18:56:16 | SqliteStorage.cpp:30 ~SqliteStorage() | ERROR: CPPSQLITE_ERROR[1000]: Unable to close database
Segmentation fault
```
Maybe you should auto create dumps on app crashes.

Let me know if you need more informations.

Bye Daniel

**Comment by egraether** [comment] 2016-06-29 12:18
Fixed with 0.7.0.15
SQLite exception was caused by not properly destructed statement.

**Closed by egraether** 2016-06-29 12:18 UTC
Labels: bug
